export const AuthActionType = {
    // set 1
    SIGNIN_SUCCESS : 'SIGNIN_SUCCESS',
    SIGNIN_FAIL : "SIGNIN_FAIL",
    LOGOUT:"LOGOUT",
    // set 2
    USER_LOADED_SUCCESS : 'USER_LOADED_SUCCESS',
    USER_LOADED_FAIL : "USER_LOADED_FAIL",
    // set 3
    AUTHENTICATED_SUCCESS: "AUTHENTICATED_SUCCESS",
    AUTHENTICATED_FAIL : "AUTHENTICATED_FAIL",

    // set 4
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAIL:"SIGNUP_FAIL",

    // set 5 
    ACTIVATION_SUCCESS:"ACTIVATION_SUCCESS",
    ACTIVATION_FAIL:"ACTIVATION_FAIL"
}