export const PasswordActionType = {
    // set 1
    PASSWORD_RESET_SUCCESS : 'PASSWORD_RESET_SUCCESS',
    PASSWORD_RESET_FAIL : "PASSWORD_RESET_FAIL",

    // set 2
    PASSWORD_RESET_CONFIRM_SUCCESS : 'PASSWORD_RESET_CONFIRM_SUCCESS',
    PASSWORD_RESET_CONFIRM_FAIL : "PASSWORD_RESET_CONFIRM_FAIL",
}